approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: false
reviewers:
  members:
  - cvsvineeth
  name: default
  required: 1

  -
name: review-by-branches
  required: 1
  members:
  - cvsvineeth
  
  conditions:
  branches:
  - int  # review if merging to staging
